suppressPackageStartupMessages({
  library(googlesheets4)
  library(tidyverse)
  library(yaml)
  library(pwr)
  library(psych)
  library(polycor)
  library(GPArotation)
  library(clue)
  library(irr)
  library(boot)
  library(BlandAltmanLeh)
  library(irrCAC)
  library(lavaan)
  library(effectsize)
  library(openxlsx)
  library(careless)
})

source("config_loader.R")
source("data_structure.R")
source("google_sheets_connector.R")
source("data_cleaner.R")
source("prepare_data.R")
source("gp_calculator.R")
source("gp_display.R")
source("gp_main.R")
source("ii_calculator.R")
source("ii_display.R")
source("ii_main.R")
source("it_calculator.R")
source("it_display.R")
source("it_main.R")
source("ceiling_floor_calculator.R")
source("ceiling_floor_display.R")
source("ceiling_floor_main.R")
source("alpha_calculator.R")
source("alpha_display.R")
source("omega_calculator.R")
source("omega_display.R")
source("reliability_main.R")
source("factor_prerequisites.R")
source("factor_suitability_calculator.R")
source("factor_suitability_display.R")
source("factor_suitability_main.R")
source("factor_number_calculator.R")
source("factor_number_display.R")
source("factor_number_main.R")
source("data_preprocessor.R")
source("efa_calculator.R")
source("efa_display.R")
source("efa_main.R")
source("validity_calculator.R")
source("validity_display.R")
source("validity_main.R")
source("interrater_calculator.R")
source("interrater_display.R")
source("interrater_main.R")
source("cfa_calculator.R")
source("cfa_display.R")
source("cfa_main.R")
source("satisficing_calculator.R")
source("satisficing_display.R")
source("satisficing_main.R")
source("response_styles_calculator.R")
source("response_styles_display.R")
source("response_styles_main.R")

cat("\n")
cat("# ===================================================\n")
cat("# Usage Examples (copy & paste)\n")
cat("# ===================================================\n")
cat("\n")
cat("# Data preparation\n")
cat("data <- prepare_data()\n")
cat("\n")
cat("# Satisficing analysis\n")
cat("sat_results <- analyze_satisficing(data)\n")
cat("clean_data <- create_clean_dataset(data$target, sat_results)\n")
cat("\n")
cat("# Response styles analysis\n")
cat("rs_results <- analyze_response_styles(data)\n")
cat("clean_data_ers <- create_rs_clean_dataset(data$target, rs_results, 'ers')\n")
cat("\n")
cat("# Item analysis\n")
cat("analyze_gp(data$target)\n")
cat("show_gp_evaluation(data$target)        # Show GP evaluation separately\n")
cat("analyze_item_correlations(data$target)\n")
cat("show_ii_evaluation(data$target)        # Show II evaluation separately\n")
cat("analyze_item_total(data$target)\n")
cat("show_it_evaluation(data$target)        # Show IT evaluation separately\n")
cat("analyze_ceiling_floor(data$target)\n")
cat("show_cf_evaluation(data$target)        # Show CF evaluation separately\n")
cat("\n")
cat("# Reliability analysis\n")
cat("analyze_reliability(data$target)\n")
cat("\n")
cat("# Factor analysis\n")
cat("check_fa_suitability(data$target)\n")
cat("determine_factors(data$target)\n")
cat("show_fn_evaluation(data$target)        # Show FN evaluation separately\n")
cat("efa_results <- analyze_efa(data$target, n_factors = 5)\n")
cat("show_efa(efa_results, gamma = 0)       # Show specific gamma result\n")
cat("show_efa_evaluation(efa_results)       # Show evaluation for all gamma\n")
cat("analyze_cfa(data$target)\n")
cat("\n")
cat("# Validity analysis\n")
cat("analyze_validity(data$target, data$rehab)\n")
cat("\n")
cat("# Interrater reliability\n")
cat("analyze_interrater(data$interrater)\n")
cat("\n")
cat("# EFA extraction method is set in analysis_config.yaml:\n")
cat("#   extraction_method: 'minres'  # or 'uls', 'pa', 'ml', 'wls', 'gls'\n")